name: Harvest Nursery
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.71883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#363c30'
    - '#a6c55e'
    - '#819844'
    - '#a2a8ac'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
