purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7723404
  brandStrength: 1
  rhythmicContrast: 0.7723404
  brandColors:
    - '#110F12'
    - '#DCD5B9'
    - '#54504D'
    - '#DF6B36'
    - '#792323'
  lightness: 0.5489362
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Harvest Nursery
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8893617
layout_spectrum: 0.9702128
